;;; preview-auto-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from preview-auto.el

(autoload 'preview-auto-mode "preview-auto" "\
Minor mode for running LaTeX preview on a timer.

This is a minor mode.  If called interactively, toggle the
`Preview-Auto mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `preview-auto-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'preview-auto-setup "preview-auto" "\
Set up keybinding and menu item for `preview-auto-mode'.
This should be run after AUCTeX has loaded to a sufficient extent,
e.g., in `LaTeX-mode-hook'.")
(register-definition-prefixes "preview-auto" '("preview-auto-"))

;;; End of scraped data

(provide 'preview-auto-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; preview-auto-autoloads.el ends here
