#!/bin/bash
set -e


# first check if this is a git repository
if [[ ! -d  "$(pwd)/.git" ]]; then
    echo "ERROR: This is not a git repository!"
    exit 0
fi

# then check if there is anything to even commit
if [[ -z "$(git status -s)" ]]; then
    echo "Nothing to commit! Exiting!"
    exit 0
fi

# add everything
echo $#
if [[ $# -gt 0 ]]; then
    git add $@
else
    git add .
fi

# then display status and prompt to continue
git status

echo
echo "Enter a commit message to continue, status for git status, diff for git diff, or type n to stop..."
while true; do
    echo
    read -p "# " MSG
    if [[ "$MSG" == "n" || "$MSG" == "exit" ]]; then
	echo "Unadding and exiting..."
	git reset HEAD --
	exit 0
    elif [[ "$MSG" == "status" || "$MSG" == "git status" ]]; then
	git status
    elif [[ "$MSG" == "diff" || "$MSG" == "git diff" ]]; then
	git diff
    elif [[ -z "$MSG" ]]; then
	echo "Not doing anything due to empty commit message!"
	echo "Unadding and exiting..."
	git reset HEAD --
	exit 0
    else
	echo "Okay, commiting and pushing!"
	break
    fi
done
echo

# then commit and push to the github
git commit -m "$MSG"
git push
