;;; auctex-cont-latexmk-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from auctex-cont-latexmk.el

(autoload 'auctex-cont-latexmk-mode "auctex-cont-latexmk" "\
If enabled, run latexmk on the current tex file.

This is a minor mode.  If called interactively, toggle the
`Auctex-Cont-Latexmk mode' mode.  If the prefix argument is
positive, enable the mode, and if it is zero or negative, disable
the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `auctex-cont-latexmk-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'auctex-cont-latexmk-toggle "auctex-cont-latexmk" "\
Toggle `auctex-cont-latexmk-mode' and its Flymake backend." t)
(register-definition-prefixes "auctex-cont-latexmk" '("auctex-cont-latexmk-"))

;;; End of scraped data

(provide 'auctex-cont-latexmk-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; auctex-cont-latexmk-autoloads.el ends here
